### ISSUE TITLE
[3.1.1+4] Incorrect getStreamUri request for media1 devices

### ISSUE THREAD

**Issue by LODYZ** [faithoflifedev/easy_onvif_workspace#72]
Hi, 

Calling media.getStreamUri() on a device of type media1 causes the device to responds with status code 500.

This is the body of the soap request:
```
<s:Body
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xmlns:xsd="http://www.w3.org/2001/XMLSchema">
		<GetStreamUri
			xmlns="http://www.onvif.org/ver10/media/wsdl">
			<StreamSetup
				xmlns="http://www.onvif.org/ver10/schema">
				<Stream
>RTP-Unicast</Stream>
				<Transport
					xmlns="http://www.onvif.org/ver10/schema">
					<Protocol>RTSP</Protocol>
				</Transport>
			</StreamSetup>
			<ProfileToken>Profile_token1</ProfileToken>
		</GetStreamUri>
	</s:Body>
```

I think that "StreamSetup" should not have the xmlns of type "schema", but rather "Stream" should have it.

This is a request that gives me status code 200:

```
<s:Body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
        <GetStreamUri xmlns="http://www.onvif.org/ver10/media/wsdl">
            <StreamSetup xmlns="http://www.onvif.org/ver10/media/wsdl">
                <Stream  xmlns="http://www.onvif.org/ver10/schema">RTP-Unicast</Stream>
                <Transport  xmlns="http://www.onvif.org/ver10/schema">
                    <Protocol xmlns="http://www.onvif.org/ver10/schema">RTSP</Protocol>
                </Transport>
            </StreamSetup>
            <ProfileToken xmlns="http://www.onvif.org/ver10/media/wsdl">Profile_token1</ProfileToken>
        </GetStreamUri>
    </s:Body>
```

Thank you

**Comment by faithoflifedev** [comment]
@LODYZ ,

I've published `easy_onvif: ^3.1.1+5` it should resolve this issue.  Please confirm.

**Comment by LODYZ** [comment]
Hi, it still doesn't work (error 500). It only works if I change the definition of "StreamSetup" and "Stream" as in the example above.
